// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRpK366r4RRO-Zptve2iTs8KbDV0lJbI',
    appId: '1:535893546108:web:7e1337924e7ba598a9e5f9',
    messagingSenderId: '535893546108',
    projectId: 'va-bot-676b4',
    authDomain: 'va-bot-676b4.firebaseapp.com',
    storageBucket: 'va-bot-676b4.firebasestorage.app',
    measurementId: 'G-79TLTYW9N1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEnrHnTd6cbds8bml3lIhHgqkhTzEjr98',
    appId: '1:535893546108:ios:816e4bc4e4fae82aa9e5f9',
    messagingSenderId: '535893546108',
    projectId: 'va-bot-676b4',
    storageBucket: 'va-bot-676b4.firebasestorage.app',
    iosBundleId: 'com.example.vaBotAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeRpK366r4RRO-Zptve2iTs8KbDV0lJbI',
    appId: '1:535893546108:web:e802c715f6e7513ca9e5f9',
    messagingSenderId: '535893546108',
    projectId: 'va-bot-676b4',
    authDomain: 'va-bot-676b4.firebaseapp.com',
    storageBucket: 'va-bot-676b4.firebasestorage.app',
    measurementId: 'G-R14BW7F7DD',
  );
}
